#ifndef BOB_THE_BLOB_COMMON_FILES_LEVELS_TYPES_CONSTS_H
#define BOB_THE_BLOB_COMMON_FILES_LEVELS_TYPES_CONSTS_H

enum{
	LevelBlueBrick,
	LevelMexican,
	LevelMax
};

#endif //BOB_THE_BLOB_COMMON_FILES_LEVELS_TYPES_CONSTS_H